# config.yaml
hyperparameters:
  max_length: 300
  model_id: "llava-hf/llava-1.5-7b-hf"
  use_lora: False
  use_qlora: True
  cuda_visible_devices: 7
  lr: 1e-4
  batch_size: 1
  max_epochs: 30
  check_val_every_n_epoch: 1
  gradient_clip_val: 1.0
  accumulate_grad_batches: 8
  warmup_steps: 50

paths:
  dir: "/media/SSD_2TB/imageclef2024/336images/"
  train_dataset_path: "/path/to/train_dataset.csv"
  valid_dataset_path: "/path/to/valid_dataset.csv"
  dev_dataset_path: "/path/to/dev_dataset.csv"
  result_path: "./result"
  output_dir: "./saved_model_earlystop_pxvls_half_df"
